#!/usr/bin/env python

import rospy
from std_msgs.msg import Header



if __name__ == "__main__":
    # start gpio

    # pull down button

    # start ros node

    # create estop publisher
    
    #main loop
    while not rospy.is_shutdown():
        # if button pressed 
            # publish msg
    
        pass