#!/usr/bin/env python




#servo control
#!/usr/bin/env python
import RPi.GPIO as GPIO
import rospy
from std_msgs.msg import Bool

#function to move servo
def Move_Servo_Callback(servoPoseCMD):
    print(servoPoseCMD)
    if servoPoseCMD.data  == False: #command to close servo
        go.ChangeDutyCycle(6.5)
    else: #command to open servo
        go.ChangeDutyCycle(11)
    
if __name__ == "__main__":

    servoFrequency = 50 #PWM frequency vlue  of the servo
    servoPin = 18 #can be any PWM pin on the pi
    GPIO.setmode(GPIO.BCM) #sets the  way the pins are selected
    GPIO.setup(servoPin, GPIO.OUT) #sets the selectedpin as an output
    go = GPIO.PWM(servoPin, servoFrequency) #sets the PWM pin and frequency

    #initialising servothe  the closed position
    go.start(11)

    # start ros node
    rospy.init_node('servo_control')

    # create subscriber
    servo_sub = rospy.Subscriber("servo_closed_state", Bool, Move_Servo_Callback)

    
    #main function
    while  not rospy.is_shutdown():
        rospy.spin()
    go.stop()
